import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Layout, Menu } from "antd";
import { Content, Header } from "antd/lib/layout/layout";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { GenerateMenu } from "./utils/menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerMenuItems = GenerateMenu([
  {
    key: "1",
    subHref: "home/welcome",
    title: "Welcome",
  },
  {
    key: "2",
    subHref: "dynamic",
    title: "Dynamic",
  },
  {
    key: "3",
    subHref: "about",
    title: "About",
  },
], "")

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout className="app-layout">
          <Header style={{ display: "flex", alignItems: "center", padding: "0 24px" }}>
            <Menu mode="horizontal" theme="dark" items={headerMenuItems} defaultSelectedKeys={["1"]} style={{ flex: "1", minWidth: 0 }} />
          </Header>
          <Content className="app-outer-content">
            <Layout className="site-layout-background app-inner-layout">
              <AntdRegistry>
                {children}
              </AntdRegistry>
            </Layout>
          </Content>
        </Layout>
      </body>
    </html>
  );
}
